services:
  database:
    image: mysql:8.0
    container_name: dell-database-c
    ports:
      - 3307:3307
    deploy:
      restart_policy:
        condition: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
    volumes:
      - databaseData:/var/lib/mysql # Persistent data volume for MySQL

  frontend:
    image: dell-frontend-prod-i:latest
    container_name: dell-frontend-prod-c
    env_file:
      - .env.prod
    depends_on:
      database:
        condition: service_started
    build:
      dockerfile: Dockerfile.prod
      args:
        - PUBLIC_NODE_ENV=${PUBLIC_NODE_ENV}
        - PUBLIC_PAGE_URL=${PUBLIC_PAGE_URL}
        - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
    deploy:
      restart_policy:
        condition: unless-stopped

volumes:
  databaseData:
