import type { paths, components } from "$lib/types/api/backend"; // generated by openapi-typescript

export type FetchFunction = (input: URL | RequestInfo, init?: RequestInit | undefined) => Promise<Response>;

export interface RedirectInterface {
	rule: (pathname: string) => boolean;
	redirect: string;
}


export type BackendSchema = components["schemas"];
export type UserModel = BackendSchema["UserModel"];

export type PageUser = Pick<UserModel, 'token' | 'name' | 'phone_number' | 'lat' | 'lon'>
